// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8rQZNM9KEaggIWU7ECICn3K4qQ0pCaps',
    appId: '1:826174653106:web:2b169e8d75963d03f9ffab',
    messagingSenderId: '826174653106',
    projectId: 'healthcare-b2d3f',
    authDomain: 'healthcare-b2d3f.firebaseapp.com',
    databaseURL: 'https://healthcare-b2d3f-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-b2d3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXxFdcQOSxtjkXGNBeGsjaYadTQWmg5n8',
    appId: '1:826174653106:ios:5eab47bd18308476f9ffab',
    messagingSenderId: '826174653106',
    projectId: 'healthcare-b2d3f',
    databaseURL: 'https://healthcare-b2d3f-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-b2d3f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXxFdcQOSxtjkXGNBeGsjaYadTQWmg5n8',
    appId: '1:826174653106:ios:5eab47bd18308476f9ffab',
    messagingSenderId: '826174653106',
    projectId: 'healthcare-b2d3f',
    databaseURL: 'https://healthcare-b2d3f-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-b2d3f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8rQZNM9KEaggIWU7ECICn3K4qQ0pCaps',
    appId: '1:826174653106:web:38f6a2415307ae3ff9ffab',
    messagingSenderId: '826174653106',
    projectId: 'healthcare-b2d3f',
    authDomain: 'healthcare-b2d3f.firebaseapp.com',
    databaseURL: 'https://healthcare-b2d3f-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-b2d3f.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_idmYGHvU4pWZLgQYTXVM78hkHdGiUIg',
    appId: '1:826174653106:android:e67b33db29485d93f9ffab',
    messagingSenderId: '826174653106',
    projectId: 'healthcare-b2d3f',
    databaseURL: 'https://healthcare-b2d3f-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-b2d3f.firebasestorage.app',
  );
}
