name: Build Flutter APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          channel: 'stable'

      - name: Install dependencies
        working-directory: ./frontend
        run: flutter pub get

      - name: Patch telephony plugin
        run: |
          TELEPHONY_DIR=ind ~/.pub-cache/hosted/pub.dev/ -name "telephony-0.2.0"
          if [ -d "$TELEPHONY_DIR" ]; then
            echo "Patching telephony plugin"
            sed -i 's/jvmTarget = '\''1.8'\''/jvmTarget = '\''11'\''/g' $TELEPHONY_DIR/android/build.gradle
            echo "kotlinOptions { jvmTarget = '11' }" >> $TELEPHONY_DIR/android/build.gradle
          fi
        shell: bash

      - name: Build APK
        working-directory: ./frontend
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: care-alert-apk
          path: frontend/build/app/outputs/flutter-apk/app-release.apk
